package maping;
// Generated 23/06/2023, 12:39:52 p. m. by Hibernate Tools 4.3.1



/**
 * Cat generated by hbm2java
 */
public class Cat  implements java.io.Serializable {


     private String catCode;
     private Pet pet;
     private String catBreed;

    public Cat() {
    }

    public Cat(Pet pet, String catBreed) {
       this.pet = pet;
       this.catBreed = catBreed;
    }
   
    public String getCatCode() {
        return this.catCode;
    }
    
    public void setCatCode(String catCode) {
        this.catCode = catCode;
    }
    public Pet getPet() {
        return this.pet;
    }
    
    public void setPet(Pet pet) {
        this.pet = pet;
    }
    public String getCatBreed() {
        return this.catBreed;
    }
    
    public void setCatBreed(String catBreed) {
        this.catBreed = catBreed;
    }




}


