package maping;
// Generated 23/06/2023, 12:39:52 p. m. by Hibernate Tools 4.3.1



/**
 * Dog generated by hbm2java
 */
public class Dog  implements java.io.Serializable {


     private String dogCode;
     private Pet pet;
     private String dogBreed;
     private boolean dogPedigree;

    public Dog() {
    }

    public Dog(Pet pet, String dogBreed, boolean dogPedigree) {
       this.pet = pet;
       this.dogBreed = dogBreed;
       this.dogPedigree = dogPedigree;
    }
   
    public String getDogCode() {
        return this.dogCode;
    }
    
    public void setDogCode(String dogCode) {
        this.dogCode = dogCode;
    }
    public Pet getPet() {
        return this.pet;
    }
    
    public void setPet(Pet pet) {
        this.pet = pet;
    }
    public String getDogBreed() {
        return this.dogBreed;
    }
    
    public void setDogBreed(String dogBreed) {
        this.dogBreed = dogBreed;
    }
    public boolean isDogPedigree() {
        return this.dogPedigree;
    }
    
    public void setDogPedigree(boolean dogPedigree) {
        this.dogPedigree = dogPedigree;
    }




}


