package maping;
// Generated 23/06/2023, 12:39:52 p. m. by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pet generated by hbm2java
 */
public class Pet  implements java.io.Serializable {


     private String petCode;
     private String petName;
     private int petBornYear;
     private String petColor;
     private String petHealthStatus;
     private Set pethospitals = new HashSet(0);
     private Dog dog;
     private Cat cat;

    public Pet() {
    }

	
    public Pet(String petCode, String petName, int petBornYear, String petColor, String petHealthStatus) {
        this.petCode = petCode;
        this.petName = petName;
        this.petBornYear = petBornYear;
        this.petColor = petColor;
        this.petHealthStatus = petHealthStatus;
    }
    public Pet(String petCode, String petName, int petBornYear, String petColor, String petHealthStatus, Set pethospitals, Dog dog, Cat cat) {
       this.petCode = petCode;
       this.petName = petName;
       this.petBornYear = petBornYear;
       this.petColor = petColor;
       this.petHealthStatus = petHealthStatus;
       this.pethospitals = pethospitals;
       this.dog = dog;
       this.cat = cat;
    }
   
    public String getPetCode() {
        return this.petCode;
    }
    
    public void setPetCode(String petCode) {
        this.petCode = petCode;
    }
    public String getPetName() {
        return this.petName;
    }
    
    public void setPetName(String petName) {
        this.petName = petName;
    }
    public int getPetBornYear() {
        return this.petBornYear;
    }
    
    public void setPetBornYear(int petBornYear) {
        this.petBornYear = petBornYear;
    }
    public String getPetColor() {
        return this.petColor;
    }
    
    public void setPetColor(String petColor) {
        this.petColor = petColor;
    }
    public String getPetHealthStatus() {
        return this.petHealthStatus;
    }
    
    public void setPetHealthStatus(String petHealthStatus) {
        this.petHealthStatus = petHealthStatus;
    }
    public Set getPethospitals() {
        return this.pethospitals;
    }
    
    public void setPethospitals(Set pethospitals) {
        this.pethospitals = pethospitals;
    }
    public Dog getDog() {
        return this.dog;
    }
    
    public void setDog(Dog dog) {
        this.dog = dog;
    }
    public Cat getCat() {
        return this.cat;
    }
    
    public void setCat(Cat cat) {
        this.cat = cat;
    }




}


