package maping;
// Generated 23/06/2023, 12:39:52 p. m. by Hibernate Tools 4.3.1



/**
 * Pethospital generated by hbm2java
 */
public class Pethospital  implements java.io.Serializable {


     private String pethCode;
     private Pet pet;
     private Veterinary veterinary;

    public Pethospital() {
    }

    public Pethospital(String pethCode, Pet pet, Veterinary veterinary) {
       this.pethCode = pethCode;
       this.pet = pet;
       this.veterinary = veterinary;
    }
   
    public String getPethCode() {
        return this.pethCode;
    }
    
    public void setPethCode(String pethCode) {
        this.pethCode = pethCode;
    }
    public Pet getPet() {
        return this.pet;
    }
    
    public void setPet(Pet pet) {
        this.pet = pet;
    }
    public Veterinary getVeterinary() {
        return this.veterinary;
    }
    
    public void setVeterinary(Veterinary veterinary) {
        this.veterinary = veterinary;
    }




}


